plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

require:
  - ./rubocop/use_from_email.rb
  - ./rubocop/custom_cop_location.rb
  - ./rubocop/attachment_download.rb
  - ./rubocop/one_class_per_file.rb

Metrics/MethodLength:
  Max: 19
  Exclude:
    - 'enterprise/lib/captain/agent.rb'
    - 'app/controllers/**/ghl*'
    - 'app/controllers/ghl/**/*'
    - 'app/jobs/**/ghl*'
    - 'app/jobs/ghl/**/*'
    - 'app/jobs/integrations/ghl/**/*'
    - 'app/models/concerns/auto_taggable.rb'
    - 'app/services/ghl/**/*'
    - 'db/migrate/20260202072500_create_ghl_subscriptions.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/controllers/**/ghl*'
    - 'app/controllers/ghl/**/*'
    - 'app/jobs/**/ghl*'
    - 'app/jobs/ghl/**/*'
    - 'app/jobs/integrations/ghl/**/*'
    - 'app/models/concerns/auto_taggable.rb'
    - 'app/services/ghl/**/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/controllers/**/ghl*'
    - 'app/controllers/ghl/**/*'
    - 'app/jobs/**/ghl*'
    - 'app/jobs/ghl/**/*'
    - 'app/jobs/integrations/ghl/**/*'
    - 'app/models/concerns/auto_taggable.rb'
    - 'app/services/ghl/**/*'

Metrics/ClassLength:
  Max: 175
  Exclude:
    - 'app/models/message.rb'
    - 'app/models/conversation.rb'
    - 'app/services/ghl/**/*'

Metrics/BlockLength:
  Max: 30
  Exclude:
    - spec/**/*
    - '**/routes.rb'
    - 'config/environments/*'
    - db/schema.rb
    - 'app/services/ghl/**/*'

RSpec/ExampleLength:
  Max: 50

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

DeskFlows/AttachmentDownload:
  Enabled: true
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Style/OptionalBooleanParameter:
  Exclude:
    - 'app/services/email_templates/db_resolver_service.rb'
    - 'app/dispatchers/dispatcher.rb'

Style/GlobalVars:
  Exclude:
    - 'config/initializers/01_redis.rb'
    - 'config/initializers/rack_attack.rb'
    - 'lib/redis/alfred.rb'
    - 'lib/global_config.rb'

Style/ClassVars:
  Exclude:
    - 'app/services/email_templates/db_resolver_service.rb'

Lint/MissingSuper:
  Exclude:
    - 'app/drops/base_drop.rb'

Lint/SymbolConversion:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
    - 'app/views/api/v1/accounts/conversations/toggle_status.json.jbuilder'

Lint/OrAssignmentToConstant:
  Exclude:
    - 'lib/redis/config.rb'

Metrics/ModuleLength:
  Exclude:
    - lib/seeders/message_seeder.rb
    - spec/support/slack_stubs.rb

Rails/HelperInstanceVariable:
  Exclude:
    - enterprise/app/helpers/captain/chat_helper.rb
    - enterprise/app/helpers/captain/chat_response_helper.rb
Rails/ApplicationController:
  Exclude:
    - 'app/controllers/api/v1/widget/messages_controller.rb'
    - 'app/controllers/dashboard_controller.rb'
    - 'app/controllers/widget_tests_controller.rb'
    - 'app/controllers/widgets_controller.rb'
    - 'app/controllers/platform_controller.rb'
    - 'app/controllers/public_controller.rb'
    - 'app/controllers/survey/responses_controller.rb'

Rails/FindEach:
  Enabled: true
  Include:
    - 'app/**/*.rb'

Rails/CompactBlank:
  Enabled: false

Rails/EnvironmentVariableAccess:
  Enabled: false

Rails/TimeZoneAssignment:
  Enabled: false

Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: false

Rails/InverseOf:
  Exclude:
    - enterprise/app/models/captain/assistant.rb

Rails/UniqueValidationWithoutIndex:
  Exclude:
    - app/models/canned_response.rb
    - app/models/telegram_bot.rb
    - enterprise/app/models/captain_inbox.rb
    - 'app/models/channel/twitter_profile.rb'
    - 'app/models/webhook.rb'
    - 'app/models/contact.rb'

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'config/application.rb'
    - 'config/initializers/monkey_patches/*'

Style/MapToHash:
  Enabled: false

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: no_mixed_keys
  EnforcedShorthandSyntax: never

RSpec/NestedGroups:
  Enabled: true
  Max: 4

RSpec/MessageSpies:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Exclude:
    - 'app/models/message.rb'

Style/GuardClause:
  Exclude:
    - 'app/builders/account_builder.rb'
    - 'app/models/attachment.rb'
    - 'app/models/message.rb'

Metrics/AbcSize:
  Max: 26
  Exclude:
    - 'app/controllers/concerns/auth_helper.rb'
    - 'app/controllers/**/ghl*'
    - 'app/controllers/ghl/**/*'
    - 'app/jobs/**/ghl*'
    - 'app/jobs/ghl/**/*'
    - 'app/jobs/integrations/ghl/**/*'
    - 'app/models/concerns/auto_taggable.rb'
    - 'app/services/ghl/**/*'
    - 'app/models/integrations/hook.rb'
    - 'app/models/canned_response.rb'
    - 'app/models/telegram_bot.rb'
    - 'db/migrate/20260202072500_create_ghl_subscriptions.rb'

Rails/RenderInline:
  Exclude:
    - 'app/controllers/swagger_controller.rb'

Rails/ThreeStateBooleanColumn:
  Exclude:
    - 'db/migrate/20230503101201_create_sla_policies.rb'

RSpec/IndexedLet:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

# we should bring this down
RSpec/MultipleExpectations:
  Max: 7

RSpec/MultipleMemoizedHelpers:
  Max: 14

# custom rules
CustomCopLocation:
  Enabled: true

Style/OneClassPerFile:
  Enabled: true

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'public/**/*'
    - 'config/initializers/bot.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'config/environments/**/*'
    - 'tmp/**/*'
    - 'storage/**/*'
    - 'db/migrate/20230426130150_init_schema.rb'

FactoryBot/SyntaxMethods:
  Enabled: false

# Disable new rules causing errors
Layout/LeadingCommentSpace:
  Enabled: false

Style/ReturnNilInPredicateMethodDefinition:
  Enabled: false

Style/RedundantParentheses:
  Enabled: false

Performance/StringIdentifierArgument:
  Enabled: false

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

Lint/LiteralAsCondition:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Rails/EnvLocal:
  Enabled: false

Rails/WhereRange:
  Enabled: false

Lint/UselessConstantScoping:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/ReceiveMessages:
  Enabled: false

FactoryBot/AssociationStyle:
  Enabled: false

Rails/EnumSyntax:
  Enabled: false

Lint/RedundantTypeConversion:
  Enabled: false

# Additional rules to disable
Rails/RedundantActiveRecordAllMethod:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: true

Style/SafeNavigationChainLength:
  Enabled: false

Lint/SafeNavigationConsistency:
  Enabled: false

Lint/CopDirectiveSyntax:
  Enabled: false

# Final set of rules to disable
FactoryBot/ExcessiveCreateList:
  Enabled: false

RSpec/MissingExpectationTargetMethod:
  Enabled: false

Performance/InefficientHashSearch:
  Enabled: false

Style/RedundantSelfAssignmentBranch:
  Enabled: false

Style/YAMLFileRead:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Style/RedundantFilterChain:
  Enabled: false

Performance/MapMethodChain:
  Enabled: false

Rails/RootPathnameMethods:
  Enabled: false

Style/SuperArguments:
  Enabled: false

# Final remaining rules to disable
Rails/Delegate:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

FactoryBot/RedundantFactoryOption:
  Enabled: false

FactoryBot/FactoryAssociationWithStrategy:
  Enabled: false

# GHL integration code — skip model validation and from_email checks
Rails/SkipsModelValidations:
  Exclude:
    - 'app/jobs/ghl/**/*'
    - 'app/jobs/integrations/ghl/**/*'
    - 'app/services/ghl/**/*'

UseFromEmail:
  Enabled: true
  Exclude:
    - 'app/models/user.rb'
    - 'app/models/contact.rb'
    - 'app/services/ghl/**/*'

Layout/LineLength:
  Max: 150
  Exclude:
    - 'app/models/concerns/auto_taggable.rb'

Lint/DuplicateBranch:
  Exclude:
    - 'app/services/ghl/**/*'

# GHL controllers use inline flash messages (not yet i18n'd)
Rails/I18nLocaleTexts:
  Exclude:
    - 'app/controllers/super_admin/ghl_tenants_controller.rb'
    - 'app/controllers/super_admin/ghl_webhook_settings_controller.rb'

# Rebrand renamed classes (Captain→Hudley, Chatwoot→DeskFlows) but not spec file paths
RSpec/SpecFilePathFormat:
  Exclude:
    - 'spec/enterprise/services/captain/**/*'
    - 'spec/lib/chatwoot_*'
    - 'spec/lib/captain/**/*'
    - 'spec/models/concerns/captain_featurable_spec.rb'
