export const DESKFLOWS_SET_USER = 'DESKFLOWS_SET_USER';
export const DESKFLOWS_RESET = 'DESKFLOWS_RESET';

export const ANALYTICS_IDENTITY = 'ANALYTICS_IDENTITY';
export const ANALYTICS_RESET = 'ANALYTICS_RESET';
